In [1]:
import pandas as pd
import numpy as np

### Importing the datasets

In [2]:
df_19 = pd.read_excel("datasets/2019_Annual_Summary.xls", skiprows=0, header=1)
df_19.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,Complete loss of Interpersonal Communication a...,System Operations,0,Unknown
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,230,230000
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,300,90382
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,230000
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,Complete loss of monitoring or control capabil...,System Operations,0,0

In [3]:
df_20 = pd.read_excel("datasets/2020_Annual_Summary.xls", skiprows=0, header=1)
df_20.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/09/2020,23:07:00,01/09/2020,23:19:00,Arkansas: Yell County;,SPP RE,"Unexpected Transmission loss within its area, ...",Severe Weather/Transmission Interruption,0,0
1,January,01/09/2020,20:45:00,01/10/2020,21:23:00,Washington: King County;,WECC,Cyber event that could potentially impact elec...,Suspicious Activity,0,0
2,January,01/09/2020,07:40:00,01/09/2020,08:48:00,Minnesota: North Dakota: Wisconsin:,MRO,Complete loss of monitoring or control capabil...,System Operations,0,0
3,January,01/09/2020,23:07:00,01/09/2020,23:18:00,Arkansas:,SPP RE,Electrical System Separation (Islanding) where...,System Operations,Unknown,Unknown
4,January,01/10/2020,14:53:00,Unknown,Unknown,Tennessee: Hamilton County;,SERC,Physical threat to its Facility excluding weat...,Suspicious Activity,Unknown,Unknown

In [4]:
df_21 = pd.read_excel("datasets/2021_Annual_Summary.xls", skiprows=0, header=1)
df_21.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/01/2021,07:04:00,01/01/2021,07:05:00,California: Alameda County;,WECC,Physical attack that could potentially impact ...,Vandalism,0,0
1,January,01/02/2021,10:28:00,01/02/2021,10:29:00,California: Butte County;,WECC,Electrical System Separation (Islanding) where...,System Operations,8,5803
2,January,01/04/2021,10:34:00,01/04/2021,10:49:00,Pennsylvania:,RF,"Unexpected Transmission loss within its area, ...",Transmission Interruption,6,3825
3,January,01/08/2021,01:26:00,01/08/2021,02:45:00,Arkansas: Prairie County;,SERC,Damage or destruction of its Facility that res...,Sabotage,Unknown,1908
4,January,01/10/2021,22:44:00,01/13/2021,16:00:00,"Texas: Anderson County, Angelina County, Dalla...",TRE,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,188000

In [5]:
df_22 = pd.read_excel("datasets/2022_Annual_Summary.xls", skiprows=0, header=1)
df_22.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/01/2022,12:36:00,01/01/2022,14:12:00,Washington: Thurston County;,WECC,Damage or destruction of a Facility within it...,System Operations,0,0
1,January,01/01/2022,12:36:00,01/02/2022,19:43:00,Washington: Thurston County;,WECC,Damage or destruction of a Facility within it...,System Operations,0,0
2,January,01/01/2022,01:01:00,Unknown,Unknown,Georgia: Clayton County;,SERC,Damage or destruction of its Facility that res...,Vandalism,0,0
3,January,01/01/2022,00:06:00,01/01/2022,05:51:00,New Hampshire: Merrimack County;,NPCC,Damage or destruction of its Facility that res...,Suspicious Activity,2,845
4,January,01/02/2022,13:21:00,01/02/2022,17:38:00,California: Tuolumne County;,WECC,Electrical System Separation (Islanding) where...,Severe Weather,3,1706

### Concatenating the dataframes

In [6]:
frames = [df_19, df_20, df_21, df_22]
df = pd.concat(frames, ignore_index=True)
df.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,Complete loss of Interpersonal Communication a...,System Operations,0,Unknown
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,230,230000
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,300,90382
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,230000
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,Complete loss of monitoring or control capabil...,System Operations,0,0

### Backing up the original dataframe

In [7]:
# Saving the data to a .csv file
df.to_csv('datasets/df_orig.csv', index=False)

### Importing the concatenated dataframe

In [8]:
df = pd.read_csv('datasets/df_orig.csv')
df.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,Complete loss of Interpersonal Communication a...,System Operations,0,Unknown
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,230,230000
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,300,90382
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,230000
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,Complete loss of monitoring or control capabil...,System Operations,0,0

### Basic information about the dataset

In [9]:
#dataset shape
print(f'The dataset has {df.shape[0]} rows and {df.shape[1]} columns.')

The dataset has 1438 rows and 11 columns.

In [10]:
# dataset columns
df.columns

Index(['Month', 'Date Event Began', 'Time Event Began', 'Date of Restoration',
       'Time of Restoration', 'Area Affected', 'NERC Region', 'Alert Criteria',
       'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected'],
      dtype='object')

### Removing the duplicated data

In [27]:
# verifying the duplicates
df.duplicated().sum()

12

In [30]:
# removing the duplicates
mask = df.duplicated()
df = df[~mask]
df.duplicated().sum()

0

### Correcting columns names

In [31]:
# replacing white space with underscore
df.columns = df.columns.str.replace(' ','_')
df.columns

Index(['Month', 'Date_Event_Began', 'Time_Event_Began', 'Date_of_Restoration',
       'Time_of_Restoration', 'Area_Affected', 'NERC_Region', 'Alert_Criteria',
       'Event_Type', 'Demand_Loss_(MW)', 'Number_of_Customers_Affected'],
      dtype='object')

In [32]:
# dataset dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1426 entries, 0 to 1437
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Month                         1426 non-null   object
 1   Date_Event_Began              1426 non-null   object
 2   Time_Event_Began              1426 non-null   object
 3   Date_of_Restoration           1426 non-null   object
 4   Time_of_Restoration           1426 non-null   object
 5   Area_Affected                 1426 non-null   object
 6   NERC_Region                   1426 non-null   object
 7   Alert_Criteria                1426 non-null   object
 8   Event_Type                    1426 non-null   object
 9   Demand_Loss_(MW)              1426 non-null   object
 10  Number_of_Customers_Affected  1425 non-null   object
dtypes: object(11)
memory usage: 133.7+ KB

In [33]:
df.isnull().sum()

Month                           0
Date_Event_Began                0
Time_Event_Began                0
Date_of_Restoration             0
Time_of_Restoration             0
Area_Affected                   0
NERC_Region                     0
Alert_Criteria                  0
Event_Type                      0
Demand_Loss_(MW)                0
Number_of_Customers_Affected    1
dtype: int64

### Dropping the 'alert criteria' and 'Nerc Region' columns

In [34]:

df = df.drop(columns=['NERC_Region',
                      'Alert_Criteria'])
df.head()

,Month,Date_Event_Began,Time_Event_Began,Date_of_Restoration,Time_of_Restoration,Area_Affected,Event_Type,Demand_Loss_(MW),Number_of_Customers_Affected
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,System Operations,0,Unknown
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,Severe Weather,230,230000
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,Severe Weather,300,90382
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",Severe Weather,Unknown,230000
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,System Operations,0,0

### Correcting the Month column

In [35]:
# There is a double January month
df['Month'].unique()

array(['January ', 'January', 'February', 'March', 'April', 'May', 'June',
       'July', 'August', 'September', 'October', 'November', 'December'],
      dtype=object)

In [36]:
# Replacing the wrong january months
df.loc[df['Month'] == 'January ','Month'] = 'January'
df['Month'].unique()

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype=object)

### Concatenating date and time events in one column

In [37]:

df['Date_Time_Event_Began'] = df['Date_Event_Began'] +' '+ df['Time_Event_Began']
df['Date_Time_Restoration'] = df['Date_of_Restoration'] +' '+ df['Time_of_Restoration']

# Dropping the old columns
df = df.drop(columns=['Date_Event_Began','Time_Event_Began','Date_of_Restoration','Time_of_Restoration'])

df.head()

,Month,Area_Affected,Event_Type,Demand_Loss_(MW),Number_of_Customers_Affected,Date_Time_Event_Began,Date_Time_Restoration
0,January,Washington:,System Operations,0,Unknown,01/05/2019 13:19:00,01/05/2019 15:07:00
1,January,Washington:,Severe Weather,230,230000,01/06/2019 03:00:00,01/09/2019 07:00:00
2,January,California: Sacramento County;,Severe Weather,300,90382,01/06/2019 17:56:00,01/06/2019 21:52:00
3,January,"Washington: King County, Thurston County, Pier...",Severe Weather,Unknown,230000,01/06/2019 01:00:00,01/06/2019 12:00:00
4,January,Michigan:,System Operations,0,0,01/07/2019 20:57:00,01/07/2019 21:32:00

In [38]:
# Setting the date/time events colmuns as datetime format
df['Date_Time_Event_Began'] = pd.to_datetime(df['Date_Time_Event_Began'], errors='coerce')
df['Date_Time_Restoration'] = pd.to_datetime(df['Date_Time_Restoration'], errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1426 entries, 0 to 1437
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Month                         1426 non-null   object
 1   Area_Affected                 1426 non-null   object
 2   Event_Type                    1426 non-null   object
 3   Demand_Loss_(MW)              1426 non-null   object
 4   Number_of_Customers_Affected  1425 non-null   object
 5   Date_Time_Event_Began         1426 non-null   datetime64[ns]
 6   Date_Time_Restoration         1232 non-null   datetime64[ns]
dtypes: datetime64[ns](2), object(5)
memory usage: 89.1+ KB

### Correcting the 'Area_Affected' column

In [39]:
# It will be removed the counties names from the columns
# Only the state affected will be stored
df['Area_Affected'].unique()

array(['Washington:', 'California: Sacramento County;',
       'Washington: King County, Thurston County, Pierce County;',
       'Michigan:', 'New Mexico: San Juan County;',
       'Montana: Valley County;', 'Maine:',
       'Missouri: Jackson County; Kansas: Johnson County;',
       'Missouri: Nebraska:', 'New Hampshire:',
       'North Carolina: South Carolina:', 'Pennsylvania:', 'California:',
       'Texas: Nueces County;', 'Nebraska:', 'Colorado: Larimer County;',
       'Ohio:', 'Utah: Iron County;', 'Louisiana: Washington Parish;',
       'Illinois: Scott County;', 'Illinois: Pike County;', 'Nevada',
       'Massachusetts', 'California', 'Arkansas', 'Michigan',
       'Pennsylvania', 'Washington', 'New Jersey', 'Utah', 'Texas',
       'Wisconsin, Minnesota, Iowa, Illinois', 'Virginia',
       'Ohio, Virginia, West Virginia', 'Ohio',
       'Connecticut, Massachusetts, New Hampshire, Maine, Vermont, Rhode Island',
       'Iowa', 'South Carolina', 'Oklahoma, Arkansas, Louisiana',
       'Oklahoma:',
       'California: Kern County, Los Angeles County; Utah: Salt Lake County; Wyoming: Converse County;',
       'Texas:', 'Colorado: Jefferson County;',
       'Texas: Midland County, Ector County, Tarrant County, Dallas County, Wichita County, Brown County;',
       'Texas: Kansas: Oklahoma:', 'California: Los Angeles County;',
       'Utah: Salt Lake County;', 'Oregon: Lane County;',
       'California: San Diego County, Los Angeles County;',
       'Nevada: Carson City, Consolidated Municipality of[19], Washoe County, Churchill County;',
       'New York: Broome County;', 'New York: Monroe County;',
       'California: Kern County;', 'California: Fresno County;',
       'Montana:', 'Virginia:', 'Oregon: Washington:',
       'Minnesota: Martin County;',
       'Mississippi: Arkansas: Texas: Louisiana:', 'Minnesota:',
       'Arizona:', 'Colorado: Clear Creek County;',
       'Alabama: Mississippi: Georgia: Florida:',
       'Arizona: Maricopa County;', 'Massachusetts: Hampden County[13];',
       'South Carolina:', 'Virginia: Surry County;', 'Indiana:',
       'Pennsylvania: Mercer County;', 'Louisiana: Texas:',
       'Texas: Harris County;', 'West Virginia:',
       'Texas: Ector County, Midland County, Tarrant County, Dallas County, Stephens County, Anderson County, McLennan County, Ellis County, Hunt County, Young County, Bell County, Limestone County, Collin County, Rockwall County, Henderson County, Parker County, Falls County, Freestone County, Kaufman County, Grayson County, Smith County;',
       'Colorado: Wyoming: Nebraska: Utah: Daggett County; New Mexico:',
       'Kentucky: Shelby County;', 'North Dakota: Minnesota:',
       'Ohio: Montgomery County, Darke County, Mercer County, Miami County, Greene County;',
       'Nevada: Washoe County;', 'Idaho: Bannock County;',
       'South Dakota: Lincoln County;', 'Texas: Bexar County;',
       'Texas: Pecos County;', 'Texas: Potter County;',
       'Texas: Collin County, Dallas County, Denton County, Palo Pinto County, Tarrant County, Ellis County, Williamson County;',
       'North Dakota: Mountrail County, Williams County;', 'Utah:',
       'California: Imperial County, Riverside County;',
       'Texas: Dallas County, Tarrant County, Collin County, Denton County;',
       'Washington: Grant County;', 'Arkansas:', 'Nevada: Clark County;',
       'Kentucky: Tennessee:', 'Alabama: Georgia:',
       'Texas: Dallas County, Denton County, Ellis County, Collin County, Ellis County, Hood County, Johnson County, Kaufman County;',
       'Oklahoma: Oklahoma County;', 'North Dakota: Williams County;',
       'Idaho: Nez Perce County;',
       'New York: Nassau County, Suffolk County;',
       'Illinois: Cook County, DeKalb County, DuPage County, Grundy County, Iroquois County, Ford County, Lake County, Kendall County, Kankakee County, Kane County, Ogle County;',
       'Idaho: Ada County;', 'Mississippi: Panola County;',
       'Texas: Louisiana: Arkansas: Mississippi:',
       'Texas: Collin County, Dallas County, Denton County, Hood County, Johnson County, Tarrant County;',
       'Texas: Lynn County;',
       'Louisiana: Acadia Parish, Avoyelles Parish, Catahoula Parish, Evangeline Parish, Grant Parish, Iberia Parish, LaSalle Parish, Natchitoches Parish, Rapides Parish, Sabine Parish, St. Landry Parish, St. Martin Parish, St. Mary Parish, St. Tammany Parish, Allen Parish, Beauregard Parish, Calcasieu Parish, Vermilion Parish, De Soto Parish, Jefferson Davis Parish, Red River Parish, Tangipahoa Parish, Vernon Parish, Washington Parish;',
       'Louisiana:', 'New York: New York County;',
       'Wisconsin: Dane County;', 'Missouri: Boone County;',
       'Wisconsin: Michigan:',
       'Michigan: Kent County, Newaygo County, Mecosta County, Montcalm County, Isabella County, Ionia County, Allegan County, Barry County;',
       'New York: Kings County, New York County, Queens County, Bronx County, Westchester County, Richmond County;',
       'Pennsylvania: Bucks County, Delaware County;',
       'New Jersey: Gloucester County;', 'California: Santa Cruz County;',
       'Nebraska: Scotts Bluff County;', 'Massachusetts:',
       'Washington: Clark County;', 'Minnesota: Chisago County;',
       'Oregon: Umatilla County;', 'Washington: Pierce County;',
       'Texas: Travis County;', 'California: Placer County;',
       'North Dakota: Mercer County;', 'Texas: Williamson County;',
       'New York: Tompkins County;', 'California: Marin County;',
       'Kentucky: Ohio County;', 'District of Columbia: Maryland:',
       'Massachusetts: Middlesex County[13];', 'Washington: King County;',
       'North Dakota:', 'Pennsylvania: New Jersey:',
       'California: Calaveras County;', 'Maryland: District of Columbia:',
       'North Carolina:', 'Wyoming: Sweetwater County;',
       'Michigan: Ionia County, Kent County, Barry County, Montcalm County, Allegan County, Ottawa County, Newaygo County;',
       'Tennessee:', 'Minnesota: Washington County;',
       'Arizona: Pima County;', 'Wisconsin: Marathon County;',
       'California: Napa County, Nevada County, Placer County, Plumas County, Sonoma County, Butte County, Yuba County;',
       'Maryland: Baltimore County;', 'California: Alameda County;',
       'Idaho: Bonneville County;', 'Missouri: Reynolds County;',
       'Texas: Hidalgo County, Cameron County;',
       'Michigan: Wayne County;', 'Kansas: Shawnee County;',
       'Connecticut: Rhode Island: Massachusetts: Vermont: New Hampshire: Maine:',
       'South Dakota: Codington County; Nebraska: Scotts Bluff County;',
       'California: Imperial County;',
       'Texas: Cass County, Cameron County, Collin County, Dallas County, Ellis County, Erath County, Hunt County, Kaufman County, Lamar County, Panola County, Rains County, Rockwall County, Rusk County, Tarrant County, Van Zandt County, Wood County;',
       'Ohio: Lorain County;', 'South Carolina: Cherokee County;',
       'Wisconsin: Brown County, Manitowoc County, Calumet County, Winnebago County, Kewaunee County, Door County, Oconto County, Marinette County, Forest County, Langlade County, Oneida County, Vilas County, Lincoln County, Oneida County, Portage County;',
       'California: Los Angeles County, Orange County, Riverside County, San Bernardino County, Ventura County, Kern County;',
       'New York:',
       'Connecticut: Maine: Massachusetts: Rhode Island: New Hampshire: Vermont:',
       'Minnesota: Sherburne County;', 'Florida: Duval County;',
       'Idaho: Elmore County;', 'Utah: California: Oregon: Wyoming:',
       'Texas: New York: Dutchess County;',
       'California: Colusa County, Lake County, Mendocino County, Napa County, Solano County, Sonoma County, Yolo County, Shasta County, Tehama County;',
       'California: Santa Clara County;',
       'Michigan: Tuscola County, Sanilac County, Huron County, St. Clair County, Macomb County, Oakland County, Wayne County, Livingston County, Washtenaw County, Monroe County;',
       'Texas: Dawson County;', 'Alabama: Covington County;',
       'Ohio: Kentucky:', 'Washington: Chelan County;',
       'Oklahoma: Stephens County;', 'Texas: Dallas County;',
       'North Dakota: Burleigh County;', 'Illinois:',
       'Arkansas: Yell County;', 'Minnesota: North Dakota: Wisconsin:',
       'Tennessee: Hamilton County;', 'Arkansas: Cross County;',
       'Arkansas: Texas:', 'Alabama: Georgia: Mississippi:',
       'Texas: Brazos County;', 'Florida: Alachua County;',
       'California: Humboldt County;', 'Nevada: Humboldt County;',
       'Florida: Manatee County;', 'North Dakota: South Dakota: Montana:',
       'Connecticut: Maine: Massachusetts: New Hampshire: Rhode Island: Vermont:',
       'Virginia: North Carolina:',
       'California: Alameda County, Contra Costa County, El Dorado County, Nevada County, Placer County, Sierra County, Santa Clara County, Napa County, Marin County, Santa Cruz County;',
       'Texas: Sterling County;', 'Oregon: Clackamas County;', 'Oregon:',
       'Alabama: Chambers County;', 'Michigan: Eaton County;',
       'Northern and Central California;',
       'South Dakota: Wyoming: Colorado:',
       'Nevada: Clark County, Washoe County;',
       'Mississippi: Rankin County;', 'Western NY', 'Alabama:',
       'Texas: Llano County;', 'Michigan: Washtenaw County;',
       'Minnesota: St. Louis County;',
       'Connecticut: Massachusetts: Rhode Island: Maine: New Hampshire: Vermont:',
       'Connecticut: Massachusetts:', 'Wisconsin: Columbia County;',
       'California: Nevada County;',
       'Connecticut: Massachusetts: Maine: New Hampshire: Rhode Island: Vermont:',
       'Delaware: Kent County, New Castle County, Sussex County; Maryland: Cecil County, Harford County, Talbot County, Kent County, Queen Anne&#39;s County, Dorchester County, Wicomico County, Worcester County, Somerset County;',
       'New Jersey: Atlantic County, Cape May County, Cumberland County, Gloucester County, Salem County;',
       'Illinois: Williamson County;', 'Nebraska: York County;',
       'Washington: Wallula', 'Texas: Cameron County;',
       'California: Stanislaus County;', 'Nevada: White Pine County;',
       'Wyoming:', 'Utah: Salt Lake City',
       'Louisiana: Acadia Parish, Iberville Parish, Jefferson Davis Parish, Concordia Parish, Winn Parish, Catahoula Parish, Terrebonne Parish, St. Mary Parish;',
       'Virginia: West Virginia:', 'Mississippi: Alabama: Georgia:',
       'Georgia:', 'South Dakota: Deuel County;',
       'Mississippi: Arkansas: Louisiana:',
       'Alabama: Georgia: Mississippi: Florida:',
       'California: Placer County, Nevada County;',
       'Oregon: Multnomah County;', 'Florida:',
       'Texas: Jefferson County;',
       'Pennsylvania: Bucks County, Chester County, Delaware County, Montgomery County, Philadelphia County, York County;',
       'Tennessee: Davidson County;', 'Nevada: Nye County;',
       'Indiana: Hendricks County;', 'Oregon: Jackson County;',
       'New York: Saratoga County;', 'Alabama: Jefferson County;',
       'Central Oklahoma', 'Texas: Kerr County;',
       'Pennsylvania: Warren County;', 'Minnesota: Hennepin County;',
       'Ohio: Franklin County;',
       'Idaho: Blaine County, Jerome County, Minidoka County, Power County;',
       'New Jersey:',
       'Michigan: Oakland County, Macomb County, Wayne County, Sanilac County, Tuscola County, Huron County, Lapeer County, Livingston County, Monroe County;',
       'Michigan: Gratiot County, Lake County, Missaukee County, Benzie County, Leelanau County, Manistee County, Wexford County, Montcalm County, Kent County, Ottawa County, Van Buren County, St. Joseph County, Arenac County, Saginaw County, Calhoun County, Branch County;',
       'Ohio: Indiana: Kentucky: West Virginia:',
       'Michigan: Houghton County;', 'Colorado: El Paso County;',
       'Kentucky: Gallatin County;', 'Delaware: New Castle County;',
       'Pennsylvania: Allegheny County, Beaver County;',
       'Kentucky: Madison County;', 'North Dakota: Mountrail County;',
       'Arkansas: Garland County;', 'California: Butte County;',
       'New York: Kings County;', 'Colorado:',
       'West Virginia: Wyoming County;', 'Washington: Thurston County;',
       'Oklahoma: Arkansas:',
       'Texas: Collin County, Dallas County, Denton County, Rockwall County, Tarrant County;',
       'New York: Niagara County', 'West Virginia: Tucker County;',
       'New York: Bronx County;',
       'Texas: Hidalgo County, Cameron County, Starr County, Kenedy County, Willacy County, Brooks County, Jim Hogg County;',
       'Texas: Nueces County, Kleberg County, Cameron County, Willacy County, Hidalgo County, Starr County, Kenedy County;',
       'Michigan: Jackson County;',
       'Texas: Cameron County, Willacy County, Hidalgo County, Starr County;',
       'California: San Diego County;',
       'Texas: Cameron County, Hidalgo County, Starr County, Willacy County;',
       'Illinois: Rock Island County;', 'Texas: Ector County;',
       'New York: Rockland County, Orange County, Sullivan County; New Jersey: Bergen County, Passaic County, Sussex County;',
       'New York: Nassau County, Suffolk County, Queens County;',
       'Delaware:',
       'New York: Dutchess County, Orange County, Ulster County;',
       'Connecticut: Massachusetts: New Hampshire: Maine: Rhode Island: Vermont:',
       'New York: Bronx County, Richmond County, Queens County, Kings County, Westchester County, New York County;',
       'North Carolina: Brunswick County, Columbus County, Pender County, Duplin County, Onslow County, Jones County, Craven County, Jones County, Beaufort County, Bertie County, Chowan County, Gates County, Perquimans County;',
       'Texas: Orange County;',
       'New York: Queens County, New York County;',
       'Iowa: Webster County, Greene County, Dallas County, Hamilton County, Boone County, Polk County, Hardin County, Story County, Jasper County, Grundy County, Marshall County, Tama County, Poweshiek County, Benton County, Iowa County, Linn County, Johnson County, Jones County, Cedar County, Muscatine County, Jackson County, Clinton County, Scott County;',
       'Illinois: Missouri:', 'Iowa:',
       'Illinois: Cook County, Will County, DuPage County, Lake County, Kane County, Grundy County, LaSalle County, DeKalb County, McHenry County, Lee County;',
       'New York: Onondaga County;',
       'Iowa: Dallas County, Polk County, Warren County, Madison County, Johnson County, Scott County; Illinois: Rock Island County, Henry County, Mercer County;',
       'Texas: El Paso County;', 'Louisiana: St. Charles Parish;',
       'California: Kern County, Kings County, Los Angeles County, Orange County, Riverside County, San Bernardino County, Santa Barbara County, Tulare County, Ventura County;',
       'Minnesota: Anoka County, Hennepin County, Ramsey County, Washington County;',
       'California: Inyo County, Kern County, Los Angeles County, Orange County, Riverside County, San Bernardino County, Tulare County, Ventura County;',
       'Washington: Snohomish County;',
       'Connecticut: New Haven County[13];',
       'Texas: Collin County, Dallas County, Denton County, Tarrant County, Ellis County, Kaufman County, Johnson County, Anderson County, Angelina County, Grayson County, Smith County, Wichita County;',
       'California: Yuba County;', 'California: Kings County;', 'Nevada:',
       'Texas: Culberson County, Reeves County;',
       'Ohio: Trumbull County;', 'Mississippi: Jasper County;',
       'Nebraska: Custer County;', 'West Virginia: Putnam County;',
       'Texas panhandle, SE NM', 'Texas: Denton County;',
       'Louisiana: Rapides Parish;', 'Texas: Louisiana:',
       'Nebraska: Douglas County, Burt County, Washington County, Dodge County, Colfax County, Saunders County, Sarpy County, Cass County, Otoe County, Johnson County, Nemaha County, Pawnee County, Richardson County;',
       'Texas: Montgomery County, Liberty County;',
       'Louisiana: Calcasieu Parish, Beauregard Parish, Iberia Parish, Acadia Parish, Evangeline Parish, Rapides Parish, St. Landry Parish, Vernon Parish;',
       'Washington: Oregon:', 'Florida: Pinellas County;',
       'Washington: Oregon: California:',
       'Washington: Kitsap County, King County, Pierce County;',
       'Oregon: Multnomah County, Washington County, Clackamas County, Marion County, Yamhill County, Polk County;',
       'Michigan: Ingham County;', 'Idaho:',
       'Alabama: Florida: Georgia: Mississippi:',
       'Florida: Escambia County;', 'Alabama: Baldwin County;',
       'Maine: Oxford County;', 'Oklahoma: Canadian County;',
       'Connecticut: Maine: Rhode Island: Massachusetts: New Hampshire: Vermont:',
       'Virginia: Hanover County;', 'Louisiana: Orleans Parish;',
       'Louisiana: Acadia Parish, Beauregard Parish, Calcasieu Parish, Evangeline Parish, Iberia Parish, Rapides Parish, Vernon Parish, Avoyelles Parish, Grant Parish, Natchitoches Parish, St. Landry Parish, St. Mary Parish, St. Tammany Parish;',
       'Louisiana: Texas: Arkansas: Mississippi:',
       'Louisiana: Lafayette Parish;', 'Florida: Polk County;',
       'Washington: Whatcom County, King County, Pierce County, Thurston County, Kittitas County, Kitsap County;',
       'Washington: Walla Walla County;', 'Kentucky:',
       'Illinois: Massac County;',
       'Wisconsin: Milwaukee County; Michigan:',
       'Oklahoma: Oklahoma County, Canadian County, Logan County, Cleveland County, Pottawatomie County;',
       'California: Los Angeles County, Riverside County, San Bernardino County, Orange County, Kern County, Ventura County;',
       'Alabama: Florida: Mississippi: Georgia:',
       'Louisiana: St. Tammany Parish, St. Mary Parish;',
       'Alabama: Baldwin County, Butler County, Clarke County, Conecuh County, Escambia County, Lee County, Lowndes County, Macon County, Montgomery County, Pike County, Russell County, Tallapoosa County, Talladega County, Washington County, Monroe County; Florida: Escambia County, Okaloosa County, Walton County, Santa Rosa County;',
       'New Hampshire: Coos County;',
       'California: San Bernardino County;',
       'Michigan: Huron County, Livingston County, Macomb County, Monroe County, Wayne County, Washtenaw County, Tuscola County, St. Clair County, Lapeer County, Oakland County;',
       'Michigan: Iosco County, Oscoda County, Ogemaw County, Livingston County, Ionia County, Barry County;',
       'Ohio: West Virginia: Virginia: Indiana:',
       'Missouri: Jackson County;',
       'Texas: Kentucky: Arizona: New Mexico: Oregon: Washington:',
       'Massachusetts: Maine: Connecticut: Rhode Island: Vermont: New Hampshire:',
       'California: Kern County, Los Angeles County, Orange County, Riverside County, San Bernardino County, San Diego County, Tulare County, Ventura County;',
       'California: Kern County, Los Angeles County, Orange County, Riverside County, San Bernardino County, Ventura County, Tulare County;',
       'Missouri: Kansas:', 'Idaho: Oregon:',
       'New Jersey: Pennsylvania: Maryland: Illinois: Delaware: District of Columbia:',
       'Connecticut: Maine: New Hampshire: Massachusetts: Rhode Island: Vermont:',
       'Arkansas: Prairie County;',
       'Texas: Anderson County, Angelina County, Dallas County, Freestone County, Henderson County, Houston County, Leon County, Nacogdoches County, Smith County, Tarrant County;',
       'Washington: Kitsap County, Thurston County, King County, Pierce County, Skagit County, Whatcom County;',
       'Oregon: Clackamas County, Multnomah County, Washington County;',
       'Washington: Idaho:', 'Georgia: Houston County;', 'Missouri:',
       'Connecticut:',
       'California: Kern County, Los Angeles County, Riverside County, San Bernardino County, Ventura County, Orange County;',
       'Texas: Louisiana: Arkansas: Pulaski County; Mississippi:',
       'Georgia: Laurens County;', 'New Hampshire: Hillsborough County;',

In [40]:
# 1. finding all the lines with contains ':', i.e., lines with county names
# 2. Spliting the strings at the ':' delimiter
# 3. Getting the firt position of the list, i.e., the state name

state_names_extracted = df.loc[df['Area_Affected'].str.contains(':'),'Area_Affected'] \
    .str.split(':')\
    .str.get(0)

# substituing the state names in the dataframe
df.loc[df['Area_Affected'].str.contains(':'),'Area_Affected'] = state_names_extracted
df['Area_Affected'].unique()

array(['Washington', 'California', 'Michigan', 'New Mexico', 'Montana',
       'Maine', 'Missouri', 'New Hampshire', 'North Carolina',
       'Pennsylvania', 'Texas', 'Nebraska', 'Colorado', 'Ohio', 'Utah',
       'Louisiana', 'Illinois', 'Nevada', 'Massachusetts', 'Arkansas',
       'New Jersey', 'Wisconsin, Minnesota, Iowa, Illinois', 'Virginia',
       'Ohio, Virginia, West Virginia',
       'Connecticut, Massachusetts, New Hampshire, Maine, Vermont, Rhode Island',
       'Iowa', 'South Carolina', 'Oklahoma, Arkansas, Louisiana',
       'Oklahoma', 'Oregon', 'New York', 'Minnesota', 'Mississippi',
       'Arizona', 'Alabama', 'Indiana', 'West Virginia', 'Kentucky',
       'North Dakota', 'Idaho', 'South Dakota', 'Wisconsin',
       'District of Columbia', 'Maryland', 'Wyoming', 'Tennessee',
       'Kansas', 'Connecticut', 'Florida',
       'Northern and Central California;', 'Western NY', 'Delaware',
       'Georgia', 'Central Oklahoma', 'Texas panhandle, SE NM', 'Vermont',
       'Rhode Island'], dtype=object)

In [41]:
# Correcting the state names
df.loc[df['Area_Affected']=='District of Columbia','Area_Affected'] = 'Washington'
df.loc[df['Area_Affected']=='Northern and Central California;','Area_Affected'] = 'California'
df.loc[df['Area_Affected']=='Western NY','Area_Affected'] = 'New York'
df.loc[df['Area_Affected']=='Central Oklahoma','Area_Affected'] = 'Oklahoma'
df.loc[df['Area_Affected']=='Texas panhandle, SE NM','Area_Affected'] = 'Texas, New Mexico'

df['Area_Affected'].unique()

array(['Washington', 'California', 'Michigan', 'New Mexico', 'Montana',
       'Maine', 'Missouri', 'New Hampshire', 'North Carolina',
       'Pennsylvania', 'Texas', 'Nebraska', 'Colorado', 'Ohio', 'Utah',
       'Louisiana', 'Illinois', 'Nevada', 'Massachusetts', 'Arkansas',
       'New Jersey', 'Wisconsin, Minnesota, Iowa, Illinois', 'Virginia',
       'Ohio, Virginia, West Virginia',
       'Connecticut, Massachusetts, New Hampshire, Maine, Vermont, Rhode Island',
       'Iowa', 'South Carolina', 'Oklahoma, Arkansas, Louisiana',
       'Oklahoma', 'Oregon', 'New York', 'Minnesota', 'Mississippi',
       'Arizona', 'Alabama', 'Indiana', 'West Virginia', 'Kentucky',
       'North Dakota', 'Idaho', 'South Dakota', 'Wisconsin', 'Maryland',
       'Wyoming', 'Tennessee', 'Kansas', 'Connecticut', 'Florida',
       'Delaware', 'Georgia', 'Texas, New Mexico', 'Vermont',
       'Rhode Island'], dtype=object)

### Replacing 'unknown' by NaN values

In [42]:
# Replacing 'unknown' by NaN values

df = df.replace(to_replace='Unknown', value=np.nan)
df.head()

,Month,Area_Affected,Event_Type,Demand_Loss_(MW),Number_of_Customers_Affected,Date_Time_Event_Began,Date_Time_Restoration
0,January,Washington,System Operations,0,NaN,2019-01-05 13:19:00,2019-01-05 15:07:00
1,January,Washington,Severe Weather,230,230000,2019-01-06 03:00:00,2019-01-09 07:00:00
2,January,California,Severe Weather,300,90382,2019-01-06 17:56:00,2019-01-06 21:52:00
3,January,Washington,Severe Weather,NaN,230000,2019-01-06 01:00:00,2019-01-06 12:00:00
4,January,Michigan,System Operations,0,0,2019-01-07 20:57:00,2019-01-07 21:32:00

### Correcting the 'Event type' column

In [43]:
df['Event_Type'].value_counts()

Severe Weather                                         445
System Operations                                      292
Vandalism                                              235
Transmission Interruption                              143
Suspicious Activity                                    132
Severe Weather/Transmission Interruption                40
Actual Physical Attack                                  36
Fuel Supply Deficiency                                  30
Cyber Event                                             19
Actual Physical Attack/Vandalism                        11
Severe Weather/Distribution Interruption                10
Generation Inadequacy                                    7
Severe Weather/Transmisison Interruption                 6
Natural Disaster                                         5
Suspicious activity                                      4
Sabotage                                                 4
Distribution Interruption                                3
Potential Physical Attack                                2
Transmission Interruption/Distribution Interruption      1
Sever Weather                                            1
Name: Event_Type, dtype: int64

In [44]:
# correcting the 'Sever Weather' typo
df.loc[df['Event_Type'] == 'Sever Weather','Event_Type'] = 'Severe Weather'

# correcting  'Suspicious activity'
df.loc[df['Event_Type'] == 'Suspicious activity','Event_Type'] = 'Suspicious Activity'

# correcting the 'Transmisison Interruption' typo
df.loc[df['Event_Type'] == 'Severe Weather/Transmisison Interruption','Event_Type'] = 'Severe Weather/Transmission Interruption'

df['Event_Type'].value_counts()

Severe Weather                                         446
System Operations                                      292
Vandalism                                              235
Transmission Interruption                              143
Suspicious Activity                                    136
Severe Weather/Transmission Interruption                46
Actual Physical Attack                                  36
Fuel Supply Deficiency                                  30
Cyber Event                                             19
Actual Physical Attack/Vandalism                        11
Severe Weather/Distribution Interruption                10
Generation Inadequacy                                    7
Natural Disaster                                         5
Sabotage                                                 4
Distribution Interruption                                3
Potential Physical Attack                                2
Transmission Interruption/Distribution Interruption      1
Name: Event_Type, dtype: int64

### Adding the 'Event_Duration' column

In [45]:
# calculating the difference between the initial and restoration dates
df['Event_Duration_(hours)'] = df['Date_Time_Restoration'] - df['Date_Time_Event_Began']

# tranforming the format deltatime to hours, rounding the result to only two decimals
df['Event_Duration_(hours)'] = [round(x.days*24 + x.seconds/(60*60),2) for x in df['Event_Duration_(hours)']]

df.head()

,Month,Area_Affected,Event_Type,Demand_Loss_(MW),Number_of_Customers_Affected,Date_Time_Event_Began,Date_Time_Restoration,Event_Duration_(hours)
0,January,Washington,System Operations,0,NaN,2019-01-05 13:19:00,2019-01-05 15:07:00,1.80
1,January,Washington,Severe Weather,230,230000,2019-01-06 03:00:00,2019-01-09 07:00:00,76.00
2,January,California,Severe Weather,300,90382,2019-01-06 17:56:00,2019-01-06 21:52:00,3.93
3,January,Washington,Severe Weather,NaN,230000,2019-01-06 01:00:00,2019-01-06 12:00:00,11.00
4,January,Michigan,System Operations,0,0,2019-01-07 20:57:00,2019-01-07 21:32:00,0.58

In [46]:
# There is an negative duration
# probably the date of restoration was entered incorrectly
df.loc[df['Event_Duration_(hours)'] <= 0]

,Month,Area_Affected,Event_Type,Demand_Loss_(MW),Number_of_Customers_Affected,Date_Time_Event_Began,Date_Time_Restoration,Event_Duration_(hours)
179,August,Texas,Distribution Interruption,752,86373,2019-08-18 16:47:00,2018-08-18 23:00:00,-8753.78

In [47]:
# fixing the date of restoration modifying the year to 2019
df.loc[df['Date_Time_Restoration'] == '2018-08-18 23:00:00','Date_Time_Restoration'] = '2019-08-18 23:00:00'

# creating again the event duration column
df['Event_Duration_(hours)'] = df['Date_Time_Restoration'] - df['Date_Time_Event_Began']
df['Event_Duration_(hours)'] = [round(x.days*24 + x.seconds/(60*60),2) for x in df['Event_Duration_(hours)']]

# checking negatives durations
df.loc[df['Event_Duration_(hours)'] <= 0]

Empty DataFrame
Columns: [Month, Area_Affected, Event_Type, Demand_Loss_(MW), Number_of_Customers_Affected, Date_Time_Event_Began, Date_Time_Restoration, Event_Duration_(hours)]
Index: []

### Converting the 'demand loss' and 'number of customers affected' columns to float type

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1426 entries, 0 to 1437
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Month                         1426 non-null   object
 1   Area_Affected                 1426 non-null   object
 2   Event_Type                    1426 non-null   object
 3   Demand_Loss_(MW)              1016 non-null   object
 4   Number_of_Customers_Affected  1241 non-null   object
 5   Date_Time_Event_Began         1426 non-null   datetime64[ns]
 6   Date_Time_Restoration         1232 non-null   datetime64[ns]
 7   Event_Duration_(hours)        1232 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(5)
memory usage: 100.3+ KB

In [49]:
df['Demand_Loss_(MW)'] = df['Demand_Loss_(MW)'].astype('float64')
df['Number_of_Customers_Affected'] = df['Number_of_Customers_Affected'].astype('float64')

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1426 entries, 0 to 1437
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Month                         1426 non-null   object
 1   Area_Affected                 1426 non-null   object
 2   Event_Type                    1426 non-null   object
 3   Demand_Loss_(MW)              1016 non-null   float64
 4   Number_of_Customers_Affected  1241 non-null   float64
 5   Date_Time_Event_Began         1426 non-null   datetime64[ns]
 6   Date_Time_Restoration         1232 non-null   datetime64[ns]
 7   Event_Duration_(hours)        1232 non-null   float64
dtypes: datetime64[ns](2), float64(3), object(3)
memory usage: 100.3+ KB

### Adding the 'year' column

In [50]:
df['Year'] = [x.year for x in df['Date_Time_Event_Began']]
df.head()

,Month,Area_Affected,Event_Type,Demand_Loss_(MW),Number_of_Customers_Affected,Date_Time_Event_Began,Date_Time_Restoration,Event_Duration_(hours),Year
0,January,Washington,System Operations,0.0,NaN,2019-01-05 13:19:00,2019-01-05 15:07:00,1.80,2019
1,January,Washington,Severe Weather,230.0,230000.0,2019-01-06 03:00:00,2019-01-09 07:00:00,76.00,2019
2,January,California,Severe Weather,300.0,90382.0,2019-01-06 17:56:00,2019-01-06 21:52:00,3.93,2019
3,January,Washington,Severe Weather,NaN,230000.0,2019-01-06 01:00:00,2019-01-06 12:00:00,11.00,2019
4,January,Michigan,System Operations,0.0,0.0,2019-01-07 20:57:00,2019-01-07 21:32:00,0.58,2019

In [51]:
# checking the 'year' column
df['Year'].value_counts()

2021    383
2022    383
2020    382
2019    278
Name: Year, dtype: int64

### Saving the final dataframe to a csv file

In [61]:
df.to_csv('datasets/df.csv', index=False)