In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
%matplotlib inline

In [2]:

df_19 = pd.read_excel("datasets/2019_Annual_Summary.xls", skiprows=0, header=1)

In [3]:
df_19.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,Complete loss of Interpersonal Communication a...,System Operations,0,Unknown
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,230,230000
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,300,90382
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,230000
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,Complete loss of monitoring or control capabil...,System Operations,0,0

In [6]:
df_19.columns

Index(['Month', 'Date Event Began', 'Time Event Began', 'Date of Restoration',
       'Time of Restoration', 'Area Affected', 'NERC Region', 'Alert Criteria',
       'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected'],
      dtype='object')

In [7]:
df_19['Year'] = 2019

In [8]:
df_19.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,Complete loss of Interpersonal Communication a...,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,Complete loss of monitoring or control capabil...,System Operations,0,0,2019

In [18]:
df_19.shape

(278, 12)

In [9]:
df_20 = pd.read_excel("datasets/2020_Annual_Summary.xls", skiprows=0, header=1)

In [10]:
df_20.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/09/2020,23:07:00,01/09/2020,23:19:00,Arkansas: Yell County;,SPP RE,"Unexpected Transmission loss within its area, ...",Severe Weather/Transmission Interruption,0,0
1,January,01/09/2020,20:45:00,01/10/2020,21:23:00,Washington: King County;,WECC,Cyber event that could potentially impact elec...,Suspicious Activity,0,0
2,January,01/09/2020,07:40:00,01/09/2020,08:48:00,Minnesota: North Dakota: Wisconsin:,MRO,Complete loss of monitoring or control capabil...,System Operations,0,0
3,January,01/09/2020,23:07:00,01/09/2020,23:18:00,Arkansas:,SPP RE,Electrical System Separation (Islanding) where...,System Operations,Unknown,Unknown
4,January,01/10/2020,14:53:00,Unknown,Unknown,Tennessee: Hamilton County;,SERC,Physical threat to its Facility excluding weat...,Suspicious Activity,Unknown,Unknown

In [11]:
df_20['Year'] = 2020
df_20.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/09/2020,23:07:00,01/09/2020,23:19:00,Arkansas: Yell County;,SPP RE,"Unexpected Transmission loss within its area, ...",Severe Weather/Transmission Interruption,0,0,2020
1,January,01/09/2020,20:45:00,01/10/2020,21:23:00,Washington: King County;,WECC,Cyber event that could potentially impact elec...,Suspicious Activity,0,0,2020
2,January,01/09/2020,07:40:00,01/09/2020,08:48:00,Minnesota: North Dakota: Wisconsin:,MRO,Complete loss of monitoring or control capabil...,System Operations,0,0,2020
3,January,01/09/2020,23:07:00,01/09/2020,23:18:00,Arkansas:,SPP RE,Electrical System Separation (Islanding) where...,System Operations,Unknown,Unknown,2020
4,January,01/10/2020,14:53:00,Unknown,Unknown,Tennessee: Hamilton County;,SERC,Physical threat to its Facility excluding weat...,Suspicious Activity,Unknown,Unknown,2020

In [19]:
df_20.shape

(383, 12)

In [12]:
df_21 = pd.read_excel("datasets/2021_Annual_Summary.xls", skiprows=0, header=1)

In [13]:
df_21.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/01/2021,07:04:00,01/01/2021,07:05:00,California: Alameda County;,WECC,Physical attack that could potentially impact ...,Vandalism,0,0
1,January,01/02/2021,10:28:00,01/02/2021,10:29:00,California: Butte County;,WECC,Electrical System Separation (Islanding) where...,System Operations,8,5803
2,January,01/04/2021,10:34:00,01/04/2021,10:49:00,Pennsylvania:,RF,"Unexpected Transmission loss within its area, ...",Transmission Interruption,6,3825
3,January,01/08/2021,01:26:00,01/08/2021,02:45:00,Arkansas: Prairie County;,SERC,Damage or destruction of its Facility that res...,Sabotage,Unknown,1908
4,January,01/10/2021,22:44:00,01/13/2021,16:00:00,"Texas: Anderson County, Angelina County, Dalla...",TRE,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,188000

In [14]:
df_21['Year'] = 2021
df_21.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/01/2021,07:04:00,01/01/2021,07:05:00,California: Alameda County;,WECC,Physical attack that could potentially impact ...,Vandalism,0,0,2021
1,January,01/02/2021,10:28:00,01/02/2021,10:29:00,California: Butte County;,WECC,Electrical System Separation (Islanding) where...,System Operations,8,5803,2021
2,January,01/04/2021,10:34:00,01/04/2021,10:49:00,Pennsylvania:,RF,"Unexpected Transmission loss within its area, ...",Transmission Interruption,6,3825,2021
3,January,01/08/2021,01:26:00,01/08/2021,02:45:00,Arkansas: Prairie County;,SERC,Damage or destruction of its Facility that res...,Sabotage,Unknown,1908,2021
4,January,01/10/2021,22:44:00,01/13/2021,16:00:00,"Texas: Anderson County, Angelina County, Dalla...",TRE,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,188000,2021

In [20]:
df_21.shape

(387, 12)

In [16]:
df_22 = pd.read_excel("datasets/2022_Annual_Summary.xls", skiprows=0, header=1)
df_22.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected
0,January,01/01/2022,12:36:00,01/01/2022,14:12:00,Washington: Thurston County;,WECC,Damage or destruction of a Facility within it...,System Operations,0,0
1,January,01/01/2022,12:36:00,01/02/2022,19:43:00,Washington: Thurston County;,WECC,Damage or destruction of a Facility within it...,System Operations,0,0
2,January,01/01/2022,01:01:00,Unknown,Unknown,Georgia: Clayton County;,SERC,Damage or destruction of its Facility that res...,Vandalism,0,0
3,January,01/01/2022,00:06:00,01/01/2022,05:51:00,New Hampshire: Merrimack County;,NPCC,Damage or destruction of its Facility that res...,Suspicious Activity,2,845
4,January,01/02/2022,13:21:00,01/02/2022,17:38:00,California: Tuolumne County;,WECC,Electrical System Separation (Islanding) where...,Severe Weather,3,1706

In [17]:
df_22['Year'] = 2022
df_22.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/01/2022,12:36:00,01/01/2022,14:12:00,Washington: Thurston County;,WECC,Damage or destruction of a Facility within it...,System Operations,0,0,2022
1,January,01/01/2022,12:36:00,01/02/2022,19:43:00,Washington: Thurston County;,WECC,Damage or destruction of a Facility within it...,System Operations,0,0,2022
2,January,01/01/2022,01:01:00,Unknown,Unknown,Georgia: Clayton County;,SERC,Damage or destruction of its Facility that res...,Vandalism,0,0,2022
3,January,01/01/2022,00:06:00,01/01/2022,05:51:00,New Hampshire: Merrimack County;,NPCC,Damage or destruction of its Facility that res...,Suspicious Activity,2,845,2022
4,January,01/02/2022,13:21:00,01/02/2022,17:38:00,California: Tuolumne County;,WECC,Electrical System Separation (Islanding) where...,Severe Weather,3,1706,2022

In [21]:
df_22.shape

(390, 12)

In [22]:
frames = [df_19, df_20, df_21, df_22]

In [23]:
df_concat = pd.concat(frames, ignore_index=True)

In [28]:
df_concat

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,Complete loss of Interpersonal Communication a...,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,Complete loss of monitoring or control capabil...,System Operations,0,0,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
1433,December,12/29/2022,16:00:00,Unknown,Unknown,Ohio:,RF,Physical threat to its Facility excluding weat...,Vandalism,2600,Unknown,2022
1434,December,12/30/2022,05:25:00,12/30/2022,14:17:00,Oregon: Sherman County;,WECC,"Unexpected Transmission loss within its area, ...",Transmission Interruption,0,0,2022
1435,December,12/30/2022,17:04:00,Unknown,Unknown,Minnesota: Washington County;,MRO,"Unexpected Transmission loss within its area, ...",Transmission Interruption,Unknown,Unknown,2022
1436,December,12/31/2022,20:00:00,01/03/2023,00:00:00,Nevada:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,3500,2022
1437,December,12/31/2022,19:00:00,01/01/2023,06:00:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,161000,2022

In [29]:
df_concat.to_csv('datasets/df_concat.csv')

## Part 2

In [13]:
df_clean1 = pd.read_csv('datasets/df_concat.csv')

In [14]:
df_clean1.head()

,Unnamed: 0,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,Complete loss of Interpersonal Communication a...,System Operations,0,Unknown,2019
1,1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,230,230000,2019
2,2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,300,90382,2019
3,3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,230000,2019
4,4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,Complete loss of monitoring or control capabil...,System Operations,0,0,2019

In [15]:
df_clean1.shape

(1438, 13)

In [16]:
df_clean1.columns

Index(['Unnamed: 0', 'Month', 'Date Event Began', 'Time Event Began',
       'Date of Restoration', 'Time of Restoration', 'Area Affected',
       'NERC Region', 'Alert Criteria', 'Event Type', 'Demand Loss (MW)',
       'Number of Customers Affected', 'Year'],
      dtype='object')

In [17]:
df_clean1 = df_clean1.drop(columns='Unnamed: 0')

In [18]:
df_clean1.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,Complete loss of Interpersonal Communication a...,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,Complete loss of monitoring or control capabil...,System Operations,0,0,2019

In [19]:
df_clean1.to_csv('datasets/df_concat.csv', index=False)

In [21]:
df_concat = pd.read_csv('datasets/df_concat.csv')
df_concat.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,Complete loss of Interpersonal Communication a...,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,Complete loss of monitoring or control capabil...,System Operations,0,0,2019

### dropping the "alert criteria" column

In [22]:
# dropping the "alert criteria" column
df_clean2 = df_concat.drop(columns='Alert Criteria')
df_clean2.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,System Operations,0,0,2019

In [23]:
df_clean2.to_csv('datasets/df_concat2.csv', index=False)

In [24]:
df_concat2 = pd.read_csv('datasets/df_concat2.csv')
df_concat2.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,System Operations,0,0,2019

In [28]:
af = df_concat2['Area Affected'].str.extract("([A-Za-z]+)\:")
af.head(10)

            0
0  Washington
1  Washington
2  California
3  Washington
4    Michigan
5      Mexico
6     Montana
7       Maine
8    Missouri
9    Missouri

In [29]:
df_concat2['Area Affected'] = df_concat2['Area Affected'].str.extract("([A-Za-z]+)\:")
df_concat2.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington,WECC,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington,WECC,Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California,WECC,Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,Washington,WECC,Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan,RF,System Operations,0,0,2019

### Changing the 'area affected' column

In [88]:
df_concat2 = pd.read_csv('datasets/df_concat2.csv')
df_concat2.shape

(1438, 11)

In [89]:
df_concat2['Area Affected'].head()

0                                          Washington:
1                                          Washington:
2                       California: Sacramento County;
3    Washington: King County, Thurston County, Pier...
4                                            Michigan:
Name: Area Affected, dtype: object

In [90]:
af = df_concat2.loc[20:40,'Area Affected']
af

20           Louisiana: Washington Parish;
21                             Washington:
22                 Illinois: Scott County;
23                               Michigan:
24                  Illinois: Pike County;
25                             California:
26                                  Nevada
27                           Massachusetts
28                              California
29                              California
30                                Arkansas
31                                Michigan
32                            Pennsylvania
33                              Washington
34                              California
35                              New Jersey
36                                    Utah
37                                   Texas
38    Wisconsin, Minnesota, Iowa, Illinois
39                                Virginia
40                            Pennsylvania
Name: Area Affected, dtype: object

In [91]:
def string_search(s, search):
    return search in str(s)

df_temp = pd.DataFrame(data = df_concat2['Area Affected'].values)
#df_temp = df_concat2['Area Affected']

mask2 = df_temp.applymap(lambda x: string_search(x, ':'))
mask2

         0
0     True
1     True
2     True
3     True
4     True
...    ...
1433  True
1434  True
1435  True
1436  True
1437  True

[1438 rows x 1 columns]

In [92]:
def split_string(series):
    return re.findall("([A-Za-z]+)\:",series)

In [93]:
df_temp = df_temp.loc[mask2.any(axis=1)].applymap(lambda x: split_string(x))
df_temp

                 0
0     [Washington]
1     [Washington]
2     [California]
3     [Washington]
4       [Michigan]
...            ...
1433        [Ohio]
1434      [Oregon]
1435   [Minnesota]
1436      [Nevada]
1437  [California]

[1409 rows x 1 columns]

In [94]:
df_concat2_test = df_concat2
df_concat2_test

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington:,WECC,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington:,WECC,Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California: Sacramento County;,WECC,Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,"Washington: King County, Thurston County, Pier...",WECC,Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan:,RF,System Operations,0,0,2019
...,...,...,...,...,...,...,...,...,...,...,...
1433,December,12/29/2022,16:00:00,Unknown,Unknown,Ohio:,RF,Vandalism,2600,Unknown,2022
1434,December,12/30/2022,05:25:00,12/30/2022,14:17:00,Oregon: Sherman County;,WECC,Transmission Interruption,0,0,2022
1435,December,12/30/2022,17:04:00,Unknown,Unknown,Minnesota: Washington County;,MRO,Transmission Interruption,Unknown,Unknown,2022
1436,December,12/31/2022,20:00:00,01/03/2023,00:00:00,Nevada:,WECC,Severe Weather,Unknown,3500,2022
1437,December,12/31/2022,19:00:00,01/01/2023,06:00:00,California: Sacramento County;,WECC,Severe Weather,Unknown,161000,2022

In [96]:
indic = df_temp.index
df_temp2 = df_concat2_test.loc[indic,'Area Affected'].str.extract("([A-Za-z]+)\:")
df_temp2

               0
0     Washington
1     Washington
2     California
3     Washington
4       Michigan
...          ...
1433        Ohio
1434      Oregon
1435   Minnesota
1436      Nevada
1437  California

[1409 rows x 1 columns]

In [97]:
df_concat2_test.loc[indic,'Area Affected'] = df_temp2.values
df_concat2_test

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington,WECC,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington,WECC,Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California,WECC,Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,Washington,WECC,Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan,RF,System Operations,0,0,2019
...,...,...,...,...,...,...,...,...,...,...,...
1433,December,12/29/2022,16:00:00,Unknown,Unknown,Ohio,RF,Vandalism,2600,Unknown,2022
1434,December,12/30/2022,05:25:00,12/30/2022,14:17:00,Oregon,WECC,Transmission Interruption,0,0,2022
1435,December,12/30/2022,17:04:00,Unknown,Unknown,Minnesota,MRO,Transmission Interruption,Unknown,Unknown,2022
1436,December,12/31/2022,20:00:00,01/03/2023,00:00:00,Nevada,WECC,Severe Weather,Unknown,3500,2022
1437,December,12/31/2022,19:00:00,01/01/2023,06:00:00,California,WECC,Severe Weather,Unknown,161000,2022

In [98]:
df_concat2_test.isnull().sum()

Month                           0
Date Event Began                0
Time Event Began                0
Date of Restoration             0
Time of Restoration             0
Area Affected                   0
NERC Region                     0
Event Type                      0
Demand Loss (MW)                0
Number of Customers Affected    1
Year                            0
dtype: int64

In [107]:
NCAcol = df_concat2_test['Number of Customers Affected']
NCAcol

0       Unknown
1        230000
2         90382
3        230000
4             0
         ...
1433    Unknown
1434          0
1435    Unknown
1436       3500
1437     161000
Name: Number of Customers Affected, Length: 1438, dtype: object

In [108]:
mask3 = NCAcol.isnull()
mask3

0       False
1       False
2       False
3       False
4       False
        ...
1433    False
1434    False
1435    False
1436    False
1437    False
Name: Number of Customers Affected, Length: 1438, dtype: bool

In [109]:
mask3.value_counts()

False    1437
True        1
Name: Number of Customers Affected, dtype: int64

In [110]:
null_NCA = NCAcol[mask3]
null_NCA

457    NaN
Name: Number of Customers Affected, dtype: object

In [112]:
df_concat2_test.loc[457,'Number of Customers Affected'] = 'Unknown'
df_concat2_test

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington,WECC,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington,WECC,Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California,WECC,Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,Washington,WECC,Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan,RF,System Operations,0,0,2019
...,...,...,...,...,...,...,...,...,...,...,...
1433,December,12/29/2022,16:00:00,Unknown,Unknown,Ohio,RF,Vandalism,2600,Unknown,2022
1434,December,12/30/2022,05:25:00,12/30/2022,14:17:00,Oregon,WECC,Transmission Interruption,0,0,2022
1435,December,12/30/2022,17:04:00,Unknown,Unknown,Minnesota,MRO,Transmission Interruption,Unknown,Unknown,2022
1436,December,12/31/2022,20:00:00,01/03/2023,00:00:00,Nevada,WECC,Severe Weather,Unknown,3500,2022
1437,December,12/31/2022,19:00:00,01/01/2023,06:00:00,California,WECC,Severe Weather,Unknown,161000,2022

In [113]:
df_concat2_test.isnull().sum()

Month                           0
Date Event Began                0
Time Event Began                0
Date of Restoration             0
Time of Restoration             0
Area Affected                   0
NERC Region                     0
Event Type                      0
Demand Loss (MW)                0
Number of Customers Affected    0
Year                            0
dtype: int64

In [114]:
df_concat2_test.to_csv('datasets/df_concat3.csv', index=False)

In [115]:
df_concat3 = pd.read_csv('datasets/df_concat3.csv')
df_concat3.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,Year
0,January,01/05/2019,13:19:00,01/05/2019,15:07:00,Washington,WECC,System Operations,0,Unknown,2019
1,January,01/06/2019,03:00:00,01/09/2019,07:00:00,Washington,WECC,Severe Weather,230,230000,2019
2,January,01/06/2019,17:56:00,01/06/2019,21:52:00,California,WECC,Severe Weather,300,90382,2019
3,January,01/06/2019,01:00:00,01/06/2019,12:00:00,Washington,WECC,Severe Weather,Unknown,230000,2019
4,January,01/07/2019,20:57:00,01/07/2019,21:32:00,Michigan,RF,System Operations,0,0,2019

In [116]:
df_concat3.shape

(1438, 11)

In [117]:
df_concat3.isnull().sum()

Month                           0
Date Event Began                0
Time Event Began                0
Date of Restoration             0
Time of Restoration             0
Area Affected                   0
NERC Region                     0
Event Type                      0
Demand Loss (MW)                0
Number of Customers Affected    0
Year                            0
dtype: int64

### Verifying the data

In [ ]:
# columns to add
# 1.event duration (hours)
# 2. year
# 3. state (from 'Area affected')
# 

# columns to remove
# 'alert criteria'

In [ ]:
# pandas concat example
# https://pandas.pydata.org/docs/reference/api/pandas.concat.html

In [ ]:
# datetime example
#https://www.geeksforgeeks.org/calculate-time-difference-in-python/

#import datetime
#    
#time1 = datetime.datetime(2018, 10, 12, 20, 15, 40)
#time2 = datetime.datetime(2015, 2, 10, 15, 41, 30)
#  
#difference = time1 - time2 
#print('Difference is : ', difference)
#    
#minutes = divmod(difference.total_seconds(), 60) 
#print('Difference in minutes: ', minutes[0],
#      'minutes', minutes[1], 'seconds')
#    
#  
#minutes = divmod(difference.seconds, 60) 
#print('Total difference in minutes: ', minutes[0], 'minutes',minutes[1], 'seconds')

In [ ]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html